USE [master]
GO

/****** Object:  Database [TerminalInterface]    Script Date: 4/8/2017 11:41:12 AM ******/
CREATE DATABASE [TerminalInterface]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TerminalInterface', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TerminalInterface.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TerminalInterface_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TerminalInterface_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TerminalInterface] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TerminalInterface].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TerminalInterface] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TerminalInterface] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TerminalInterface] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TerminalInterface] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TerminalInterface] SET ARITHABORT OFF 
GO

ALTER DATABASE [TerminalInterface] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TerminalInterface] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TerminalInterface] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TerminalInterface] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TerminalInterface] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TerminalInterface] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TerminalInterface] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TerminalInterface] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TerminalInterface] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TerminalInterface] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TerminalInterface] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TerminalInterface] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TerminalInterface] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TerminalInterface] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TerminalInterface] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TerminalInterface] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TerminalInterface] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TerminalInterface] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TerminalInterface] SET  MULTI_USER 
GO

ALTER DATABASE [TerminalInterface] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TerminalInterface] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TerminalInterface] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TerminalInterface] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TerminalInterface] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TerminalInterface] SET QUERY_STORE = OFF
GO

USE [TerminalInterface]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TerminalInterface] SET  READ_WRITE 
GO


